/**
 * This file has no copyright assigned and is placed in the Public Domain.
 * This file is part of the mingw-w64 runtime package.
 * No warranty is given; refer to the file DISCLAIMER.PD within this package.
 */

#ifdef __WIDL__
#pragma winrt ns_prefix
#endif

import "inspectable.idl";

// found in eventtoken.h in MSDK
typedef struct EventRegistrationToken {
  UINT64 Value;
} EventRegistrationToken;

// found in asyncinfo.h in MSDK
typedef [v1_enum] enum AsyncStatus {
  Started,
  Completed,
  Canceled,
  Error
} AsyncStatus;

namespace Windows {
  namespace Foundation {
    interface IAsyncInfo;
    interface IAsyncAction;
    interface IAsyncOperation<T>;
    struct    DateTime;

    namespace Collections {
      interface IPropertySet;
    }
  }
}

namespace Windows {
  namespace Foundation {
    struct DateTime {
      UINT64 UniversalTime;
    };

    struct TimeSpan {
      INT64 Duration;
    };

    [uuid(00000036-0000-0000-C000-000000000046)]
    interface IAsyncInfo : IInspectable
    {
      [propget] HRESULT Id(unsigned int *id);
      [propget] HRESULT Status(AsyncStatus *status);
      [propget] HRESULT ErrorCode(HRESULT *errorCode);
      HRESULT Cancel();
      HRESULT Close();
    }

    [uuid(a4ed5c81-76c9-40bd-8be6-b1d90fb20ae7)]
    delegate HRESULT AsyncActionCompletedHandler(IAsyncAction *asyncAction, AsyncStatus status);

    [uuid(5a648006-843a-4da9-865b-9d26e5dfad7b)]
    interface IASyncAction : IAsyncInfo {
      [propput] HRESULT Completed(AsyncActionCompletedHandler* handler);
      [propget] HRESULT Completed(AsyncActionCompletedHandler** handler);
      HRESULT GetResults();
    }

#ifdef __WIDL__
        [
            uuid(fcdcf02c-e5d8-4478-915a-4d90b74b83a5)
        ]
        delegate HRESULT AsyncOperationCompletedHandler<T>(Windows.Foundation.IAsyncOperation<T> *asyncInfo, AsyncStatus asyncStatus);

        [uuid("9fc2b0bb-e446-44e2-aa61-9cab8f636af2")]
        interface IAsyncOperation<T> : IInspectable {
            [propput] HRESULT Completed(AsyncOperationCompletedHandler<T>* handler);
            [propget] HRESULT Completed(AsyncOperationCompletedHandler<T>** handler);
            HRESULT GetResults(T* result);
        }

        [
            uuid(9de1c535-6ae1-11e0-84e1-18a905bcc53f)
        ]
        delegate HRESULT EventHandler<T>([in] IInspectable *sender, [in] T args);

        [
            uuid(9de1c534-6ae1-11e0-84e1-18a905bcc53f)
        ]
        // parameter order seems inverted for TypedEventHandler<DeviceWatcher*, DeviceInformation*>
        delegate HRESULT TypedEventHandler<TSender,TResult>(TResult args, TSender sender);

        namespace Collections
        {
            [
                uuid(6a79e863-4300-459a-9966-cbb660963ee1)
            ]
            interface IIterator<T> : IInspectable
            {
                [propget] HRESULT Current([out, retval] T *value);
                [propget] HRESULT HasCurrent([out, retval] BOOL *value);
                HRESULT MoveNext([out, retval] BOOL *value);
                HRESULT GetMany([in] UINT32 count, [out] T *items, [out, retval] UINT32 *value);
            }

            [
                uuid(faa585ea-6214-4217-afda-7f46de5869b3)
            ]
            interface IIterable<T> : IInspectable
            {
                HRESULT First([out, retval] Windows.Foundation.Collections.IIterator<T> **value);
            }

            [
                uuid(bbe1fa4c-b0e3-4583-baef-1f1b2e483e56)
            ]
            interface IVectorView<T> : IInspectable
            {
                HRESULT GetAt([in] UINT32 index, [out, retval] T *value);
                [propget] HRESULT Size([out, retval] UINT32 *value);
                HRESULT IndexOf([in, optional] T element, [out] UINT32 *index, [out, retval] BOOLEAN *value);
                HRESULT GetMany([in] UINT32 start_index, [in] UINT32 itemsLength, [out] T **items, [out, retval] UINT32 *value);
            }
        }
#endif
  }
}

namespace Windows {
    namespace Foundation {
        declare {
            interface Windows.Foundation.Collections.IVectorView<HSTRING>;

            interface Windows.Foundation.Collections.IIterable<HSTRING>;
            interface Windows.Foundation.Collections.IIterator<HSTRING>;

            interface Windows.Foundation.IAsyncOperation<UINT32>;
            interface Windows.Foundation.AsyncOperationCompletedHandler<UINT32>;
        }
    }
}
